### ISSUE TITLE
Back Button not working after onExitSecondScreen() 

### ISSUE THREAD

**Issue by ab5593** [moyokoo/YoutubeVideoSample#3]
The back button works fine when its in potrait mode.. but after i go fullscreen `onEnterSecondScreen()` and press `fullScreenIv` button the screen orientation changes to potrait as expected, but the back button becomes non functional.. 

Any suggestions will be of great help...

**Comment by mikaelzero** [comment]
demo or your project

any happens when u click back button

debug [fullScreenChange](https://github.com/moyokoo/YoutubeVideoSample/blob/master/app/src/main/java/com/example/m/youtu/YouTuDraggingView.java#L723) ，see value of isLandscapeToPortrait and activity's Orientation

**Comment by ab5593** [comment]
the back button becomes non functional as there were no code in it after the orientation change happens..

**Comment by ab5593** [comment]
modified the onKeyDown method as below: 

     @Override
     public boolean onKeyDown(int keyCode, KeyEvent event) {

    if (keyCode == KeyEvent.KEYCODE_BACK && mYouTuDraggingView.getNowStateScale() == 1f) {
      int orientation = getResources().getConfiguration().orientation;

        if (orientation == Configuration.ORIENTATION_PORTRAIT){
            // In portrait
          toolbar.setVisibility(View.VISIBLE);
        //  showSystemUI();
            mYouTuDraggingView.goMin();
            return true;
        } else {
        // In landscape

      }

    }
      return mYouTuDraggingView.handleKeyDown(keyCode) || super.onKeyDown(keyCode, event);
      } 

Also i disabled the `onBackPressed() ` method..

My issue got resolved but i wonder though... is it the correct way...?

**Comment by mikaelzero** [comment]
`onBackPressed ` is a method associated with a player

If ur modified code is correct ,maybe there is a bug with `isPortraitToLandscape`

and ur code is correct

**Comment by ab5593** [comment]
Thank you for your prompt reply..  

also if you could guide me on how to embed youtube videos directly.. with a youtube video link ( for e.g youtube.com/watch?v=sOmEv1de0) currently we code the mp4 file to play the video.... the reason why I am asking this is if we skip the video by onStartTrackingTouch and onStopTrackingTouch the video doesn't get continued from the new seek position as it is still buffering.. it just stops and when we click the play button it returns to the start of the video..

**Comment by mikaelzero** [comment]
It seems that your problem is the player's problem.

i use [ArtPlayer](https://github.com/maiwenchang/ArtPlayer) in my demo,You can replace the player code as you want.

**Comment by ab5593** [comment]
I have used the same player as the demo.. Does Artplayer support embedding Youtube videos where we code the link of the video..
(For e.g : youtube.com/watch?v=sOmEv1de0)

**Comment by mikaelzero** [comment]
Player problem you can go to consult [issue](https://github.com/maiwenchang/ArtPlayer/issues)

of course,you can use another player like [ijkplayer](https://github.com/bilibili/ijkplayer) to test youtube video

**Comment by ab5593** [comment]
Thank you...
