### ISSUE TITLE
Secondary progress Bar (Buffering) not visible..

### ISSUE THREAD

**Issue by ab5593** [moyokoo/YoutubeVideoSample#4]
The code in the [YouTubeControlPanel.java](https://github.com/moyokoo/YoutubeVideoSample/blob/master/app/src/main/java/com/example/m/youtu/YoutubeControlPanel.java)

     @Override
    public void onBufferingUpdate(int progress) {
        if (progress != 0) bottom_seek_progress.setSecondaryProgress(progress);
     }

does not show the secondary progress bar in the videoView..

How to show buffering bar on top of the seekBar?

**Comment by mikaelzero** [comment]
work in demo?

if it's work,maybe the problem is video url error

**Comment by ab5593** [comment]
Not working in demo too..

**Comment by mikaelzero** [comment]
I have time to see it.

**Comment by mikaelzero** [comment]
I tested that the bottom_seek_progressr and SecondaryProgres of the demo was displayed

**Comment by ab5593** [comment]
strange issue... i updated my video on the github repository and updated the `mVideoView.setup("MY_SERVER_VIDEO_LINK");`  with `mVideoView.setup("MY_GITHUB_VIDEO_LINK");` in the `playVideo();` method.. Now the Secondary Buffering Bar shows correctly... It seems that its my server issue..  thanks a ton for the update @moyokoo ...
