### ISSUE TITLE
Set height of min view

### ISSUE THREAD

**Issue by SaifulIslam123** [moyokoo/YoutubeVideoSample#9]
when I minimize  dragview it always shows same height of min view. I want to increase the height of min view. 

Can you please tell me how i can change the height of the min view of dragview?

**Comment by mikaelzero** [comment]
try modify this

https://github.com/MikaelZero/YoutubeVideoSample/blob/3407519933e303ea05e5575df834a19f854c75d5/app/src/main/java/com/example/m/youtu/YouTuDraggingView.java#L93

**Comment by SaifulIslam123** [comment]
it works , Thanks @MikaelZero
